{"abstract":[{"text":"Choose which type of actions to populate the wheel with","type":"text"}],"metadata":{"title":"networkType","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ExternalNetworkType","preciseIdentifier":"s:7AlltKit19ExternalNetworkTypeO","kind":"typeIdentifier"}],"externalID":"s:7AlltKit0A14ActionMenuViewC11networkTypeAA015ExternalNetworkG0Ovp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltactionmenuview\/networktype"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ExternalNetworkType","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworkType","preciseIdentifier":"s:7AlltKit19ExternalNetworkTypeO","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/networkType"},"kind":"symbol","references":{"doc://tv.allt.AlltKit/documentation/AlltKit/ExternalNetworkType":{"url":"\/documentation\/alltkit\/externalnetworktype","kind":"symbol","title":"ExternalNetworkType","navigatorTitle":[{"kind":"identifier","text":"ExternalNetworkType"}],"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ExternalNetworkType","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworkType"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView/networkType":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/networkType","abstract":[{"text":"Choose which type of actions to populate the wheel with","type":"text"}],"role":"symbol","url":"\/documentation\/alltkit\/alltactionmenuview\/networktype","kind":"symbol","type":"topic","title":"networkType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkType"},{"text":": ","kind":"text"},{"text":"ExternalNetworkType","kind":"typeIdentifier","preciseIdentifier":"s:7AlltKit19ExternalNetworkTypeO"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView":{"title":"AlltActionMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AlltActionMenuView","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltactionmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","abstract":[{"text":"User Interface component for Allt, specific to one External Network action type.   Drop this into your view hierarchy and set the ","type":"text"},{"code":"delegate","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" properties.  The ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" property is used to push the modal Allt User Interface.  Connect the ","type":"text"},{"type":"codeVoice","code":"showHistory"},{"text":" and ","type":"text"},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AlltActionMenuView","kind":"identifier"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AlltActionMenuView","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/title"},{"value":[{"text":"AlltActionMenuView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/fragments"},{"value":[{"kind":"identifier","text":"AlltActionMenuView"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/navigatorTitle"}]}]}