{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/networkType"]},{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/toggle(_:)"],"title":"Instance Methods"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltactionmenuview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltactionmenuview"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AlltActionMenuView","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"AlltActionMenuView","externalID":"c:@M@AlltKit@objc(cs)AlltActionMenuView","roleHeading":"Class","modules":[{"name":"AlltKit"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltActionMenuView"}],"navigatorTitle":[{"text":"AlltActionMenuView","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"User Interface component for Allt, specific to one External Network action type.   Drop this into your view hierarchy and set the "},{"type":"codeVoice","code":"delegate"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"type":"codeVoice","code":"showHistory"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":"s to appropriate buttons in your User Interface."}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/tv.allt.AlltKit\/objc(pl)NSCoding","doc:\/\/tv.allt.AlltKit\/objc(pl)NSObject","doc:\/\/tv.allt.AlltKit\/objc(pl)CALayerDelegate","doc:\/\/tv.allt.AlltKit\/s7CVarArgP","doc:\/\/tv.allt.AlltKit\/s28CustomDebugStringConvertibleP","doc:\/\/tv.allt.AlltKit\/s23CustomStringConvertibleP","doc:\/\/tv.allt.AlltKit\/SQ","doc:\/\/tv.allt.AlltKit\/SH","doc:\/\/tv.allt.AlltKit\/s8SendableP","doc:\/\/tv.allt.AlltKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/tv.allt.AlltKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tv.allt.AlltKit\/objc(pl)UIAppearance","doc:\/\/tv.allt.AlltKit\/objc(pl)UIAppearanceContainer","doc:\/\/tv.allt.AlltKit\/objc(pl)UICoordinateSpace","doc:\/\/tv.allt.AlltKit\/objc(pl)UIDynamicItem","doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusEnvironment","doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusItem","doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusItemContainer","doc:\/\/tv.allt.AlltKit\/objc(pl)UILargeContentViewerItem","doc:\/\/tv.allt.AlltKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tv.allt.AlltKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/tv.allt.AlltKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/tv.allt.AlltKit\/5UIKit23UITraitChangeObservableP","doc:\/\/tv.allt.AlltKit\/objc(pl)UITraitEnvironment","doc:\/\/tv.allt.AlltKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"references":{"doc://tv.allt.AlltKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://tv.allt.AlltKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://tv.allt.AlltKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/SQ"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView/toggle(_:)":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/toggle(_:)","role":"symbol","abstract":[{"type":"text","text":"Toggle the AlltMenuView"}],"title":"toggle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/alltkit\/alltactionmenuview\/toggle(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toggle","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView":{"navigatorTitle":[{"kind":"identifier","text":"AlltActionMenuView"}],"title":"AlltActionMenuView","abstract":[{"type":"text","text":"User Interface component for Allt, specific to one External Network action type.   Drop this into your view hierarchy and set the "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"text":" properties.  The ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":"s to appropriate buttons in your User Interface."}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","type":"topic","url":"\/documentation\/alltkit\/alltactionmenuview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltActionMenuView"}]},"doc://tv.allt.AlltKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://tv.allt.AlltKit/s7CVarArgP":{"identifier":"doc:\/\/tv.allt.AlltKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://tv.allt.AlltKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tv.allt.AlltKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://tv.allt.AlltKit/objc(pl)NSObject":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://tv.allt.AlltKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"abstract":[{"text":"User Interface component for Allt - drop this into your view hierarchy and set the ","type":"text"},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"code":"presentingViewController","type":"codeVoice"},{"text":" properties.  The ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"code":"IBAction","type":"codeVoice"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltMenuView"}],"navigatorTitle":[{"kind":"identifier","text":"AlltMenuView"}],"title":"AlltMenuView","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview"},"doc://tv.allt.AlltKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://tv.allt.AlltKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView/networkType":{"title":"networkType","abstract":[{"type":"text","text":"Choose which type of actions to populate the wheel with"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView\/networkType","type":"topic","kind":"symbol","url":"\/documentation\/alltkit\/alltactionmenuview\/networktype","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExternalNetworkType","preciseIdentifier":"s:7AlltKit19ExternalNetworkTypeO"}]},"doc://tv.allt.AlltKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://tv.allt.AlltKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://tv.allt.AlltKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://tv.allt.AlltKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://tv.allt.AlltKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/s8SendableP","title":"Swift.Sendable"},"doc://tv.allt.AlltKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://tv.allt.AlltKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://tv.allt.AlltKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://tv.allt.AlltKit/SH":{"identifier":"doc:\/\/tv.allt.AlltKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://tv.allt.AlltKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://tv.allt.AlltKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://tv.allt.AlltKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://tv.allt.AlltKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://tv.allt.AlltKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"AlltActionMenuView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"AlltActionMenuView"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"AlltActionMenuView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltActionMenuView","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","text":"AlltMenuView","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltMenuView","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/title","op":"replace","value":"AlltActionMenuView"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/fragments","value":[{"text":"AlltActionMenuView","kind":"identifier"}]},{"op":"replace","value":"AlltMenuView","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title"},{"value":[{"kind":"identifier","text":"AlltMenuView"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments"}]}]}