{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/tv.allt.AlltKit\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/tv.allt.AlltKit\/objc(pl)NSObject","doc:\/\/tv.allt.AlltKit\/s7CVarArgP","doc:\/\/tv.allt.AlltKit\/s28CustomDebugStringConvertibleP","doc:\/\/tv.allt.AlltKit\/s23CustomStringConvertibleP","doc:\/\/tv.allt.AlltKit\/SQ","doc:\/\/tv.allt.AlltKit\/SH"],"kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerConnection"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}],"externalID":"c:@M@AlltKit@objc(cs)AlltServerConnection","title":"AlltServerConnection","symbolKind":"class","modules":[{"name":"AlltKit"}],"navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit"]]},"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"type":"codeVoice","code":"AlltServer"},{"type":"text","text":".  The "},{"type":"codeVoice","code":"currentAlltCode"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/alltCodeMediaType","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/currentAlltCode","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/playbackState","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/uuid"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltserverconnection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverconnection"]}],"references":{"doc://tv.allt.AlltKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/s28CustomDebugStringConvertibleP"},"doc://tv.allt.AlltKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/objc(cs)NSObject","title":"NSObject"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/uuid":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"type":"text","text":"UUID of the AlltServer that this AlltClient is connected to"}],"url":"\/documentation\/alltkit\/alltserverconnection\/uuid","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/uuid","title":"uuid","role":"symbol"},"doc://tv.allt.AlltKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/currentAlltCode":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/currentAlltCode","abstract":[{"text":"Current allt-code picked up on the network","type":"text"}],"role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection\/currentalltcode","kind":"symbol","type":"topic","title":"currentAlltCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentAlltCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://tv.allt.AlltKit/objc(pl)NSObject":{"identifier":"doc:\/\/tv.allt.AlltKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","abstract":[],"url":"\/documentation\/alltkit\/alltserverconnection\/init","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/init","title":"init","role":"symbol"},"doc://tv.allt.AlltKit/SH":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/SH","title":"Swift.Hashable"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"type":"codeVoice","code":"AlltServer"},{"type":"text","text":".  The "},{"type":"codeVoice","code":"currentAlltCode"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tv.allt.AlltKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://tv.allt.AlltKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/tv.allt.AlltKit\/SQ","title":"Swift.Equatable"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/playbackState":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/playbackState","abstract":[{"text":"Current playback state","type":"text"}],"role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection\/playbackstate","kind":"symbol","type":"topic","title":"playbackState","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AlltServerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState"},{"text":"?","kind":"text"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/alltCodeMediaType":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/alltCodeMediaType","abstract":[],"role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection\/alltcodemediatype","kind":"symbol","type":"topic","title":"alltCodeMediaType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alltCodeMediaType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AlltServerConnection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AlltServerConnection","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AlltServerConnection","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/init"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/tv.allt.AlltKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerConnection"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","value":"AlltServerConnection"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","value":[{"kind":"identifier","text":"AlltServerConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/navigatorTitle","value":[{"kind":"identifier","text":"AlltServerConnection"}]}]}]}