{"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeActive()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeInactive()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didUpdateAlltContent()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/endAdvertizing(identifier:)","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/receivedPosterURLs(small:large:)","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showAdvertizing(identifier:onClickURL:)"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltMenuViewDelegate","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AlltMenuViewDelegate","kind":"identifier"}],"symbolKind":"protocol","navigatorTitle":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"AlltKit"}],"role":"symbol","title":"AlltMenuViewDelegate","platforms":[]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/receivedPosterURLs(small:large:)":{"kind":"symbol","abstract":[{"text":"Called when Allt has resolved the currently playing content, passing URLs for both small and large poster representations.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/receivedPosterURLs(small:large:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedPosterURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"small"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"large","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"receivedPosterURLsWithSmall:large:","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/alltkit\/alltmenuviewdelegate\/receivedposterurls(small:large:)","role":"symbol","title":"receivedPosterURLs(small:large:)","type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/endAdvertizing(identifier:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/endAdvertizing(identifier:)","navigatorTitle":[{"text":"endAdvertizingWithIdentifier:","kind":"identifier"}],"role":"symbol","title":"endAdvertizing(identifier:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endAdvertizing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[{"text":"Called when allt-enabled advertizing has finished playing","type":"text"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate\/endadvertizing(identifier:)"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/didUpdateAlltContent()":{"kind":"symbol","required":true,"deprecated":true,"type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didUpdateAlltContent()","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/didupdatealltcontent()","abstract":[{"type":"text","text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdateAlltContent"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"didUpdateAlltContent","kind":"identifier"}],"role":"symbol","title":"didUpdateAlltContent()"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"abstract":[],"title":"AlltMenuViewDelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate","type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/didBecomeInactive()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeInactive()","navigatorTitle":[{"text":"didBecomeInactive","kind":"identifier"}],"role":"symbol","title":"didBecomeInactive()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBecomeInactive","kind":"identifier"},{"kind":"text","text":"()"}],"deprecated":true,"abstract":[{"text":"Called when Allt has discovered that content is no longer playing","type":"text"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate\/didbecomeinactive()"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/didBecomeActive()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didBecomeActive","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeActive()","type":"topic","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/didbecomeactive()","kind":"symbol","role":"symbol","title":"didBecomeActive()","navigatorTitle":[{"kind":"identifier","text":"didBecomeActive"}],"required":true,"abstract":[{"type":"text","text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed"}],"deprecated":true},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/showAdvertizing(identifier:onClickURL:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAdvertizing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onClickURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"title":"showAdvertizing(identifier:onClickURL:)","role":"symbol","type":"topic","deprecated":true,"required":true,"navigatorTitle":[{"text":"showAdvertizingWithIdentifier:onClickURL:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when allt-enabled advertizing is playing on the server"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate\/showadvertizing(identifier:onclickurl:)","kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showAdvertizing(identifier:onClickURL:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AlltMenuViewDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeActive()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeInactive()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didUpdateAlltContent()","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/endAdvertizing(identifier:)","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/receivedPosterURLs(small:large:)","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showAdvertizing(identifier:onClickURL:)"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"AlltMenuViewDelegate","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1receivedPosterURLs(small:large:)\/title","value":"receivedPosterURLsWithSmall:large:","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1receivedPosterURLs(small:large:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"receivedPosterURLsWithSmall:large:"}],"op":"replace"},{"value":"endAdvertizingWithIdentifier:","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1endAdvertizing(identifier:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"endAdvertizingWithIdentifier:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1endAdvertizing(identifier:)\/fragments"},{"value":"didUpdateAlltContent","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didUpdateAlltContent()\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didUpdateAlltContent()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didUpdateAlltContent","kind":"identifier"}],"op":"replace"},{"value":"AlltMenuViewDelegate","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","value":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"op":"replace"},{"value":"didBecomeInactive","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeInactive()\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeInactive()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didBecomeInactive"}]},{"value":"didBecomeActive","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeActive()\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeActive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didBecomeActive"}]},{"op":"replace","value":"showAdvertizingWithIdentifier:onClickURL:","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showAdvertizing(identifier:onClickURL:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"showAdvertizingWithIdentifier:onClickURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showAdvertizing(identifier:onClickURL:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}