{"abstract":[{"type":"text","text":"Enumerates the possible states of the AlltServer"}],"metadata":{"title":"AlltServerState","navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"modules":[{"name":"AlltKit"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerState","kind":"identifier"}],"externalID":"c:@M@AlltKit@E@AlltServerState"},"variants":[{"paths":["\/documentation\/alltkit\/alltserverstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltserverstate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/offline","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/paused","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/playing","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/ready","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/stopped"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/description()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/Equatable-Implementations","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/tv.allt.AlltKit\/SQ","doc:\/\/tv.allt.AlltKit\/SH","doc:\/\/tv.allt.AlltKit\/SY"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerState"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/description()":{"title":"description()","abstract":[{"text":"The alltServer is  connected to a network but no media is currently being played","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/description()","role":"symbol","url":"\/documentation\/alltkit\/alltserverstate\/description()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/alltkit\/alltserverstate\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/init(rawValue:)","title":"init(rawValue:)","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/RawRepresentable-Implementations","url":"\/documentation\/alltkit\/alltserverstate\/rawrepresentable-implementations"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","navigatorTitle":[{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverstate","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerState","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/stopped":{"role":"symbol","url":"\/documentation\/alltkit\/alltserverstate\/stopped","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"kind":"symbol","title":"AlltServerState.stopped","navigatorTitle":[{"text":"AlltServerStateStopped","kind":"identifier"}],"abstract":[{"type":"text","text":"The alltServer is  connected to a network and media is currently playing"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/stopped"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/ready":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/ready","abstract":[{"type":"text","text":"The alltServer is not connected to a network"}],"role":"symbol","url":"\/documentation\/alltkit\/alltserverstate\/ready","kind":"symbol","type":"topic","title":"AlltServerState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"navigatorTitle":[{"kind":"identifier","text":"AlltServerStateReady"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/Equatable-Implementations","url":"\/documentation\/alltkit\/alltserverstate\/equatable-implementations"},"doc://tv.allt.AlltKit/SH":{"identifier":"doc:\/\/tv.allt.AlltKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/playing":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/playing","abstract":[{"text":"The alltServer is  connected to a network and media is currently paused","type":"text"}],"role":"symbol","url":"\/documentation\/alltkit\/alltserverstate\/playing","kind":"symbol","type":"topic","title":"AlltServerState.playing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playing","kind":"identifier"}],"navigatorTitle":[{"text":"AlltServerStatePlaying","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/SY":{"identifier":"doc:\/\/tv.allt.AlltKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://tv.allt.AlltKit/SQ":{"identifier":"doc:\/\/tv.allt.AlltKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/paused":{"title":"AlltServerState.paused","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltserverstate\/paused","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/paused","abstract":[{"type":"text","text":"The alltServer is  connected to a network but no media has been played"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AlltServerStatePaused","kind":"identifier"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/offline":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/offline","navigatorTitle":[{"text":"AlltServerStateOffline","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltserverstate\/offline","title":"AlltServerState.offline","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AlltServerState","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"AlltServerState"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/offline","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/paused","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/playing","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/ready","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/stopped"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerState","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","value":"AlltServerState","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/navigatorTitle","value":[{"kind":"identifier","text":"AlltServerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1stopped\/title","value":"AlltServerStateStopped","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1stopped\/fragments","value":[{"text":"AlltServerStateStopped","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1ready\/title","value":"AlltServerStateReady","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1ready\/fragments","value":[{"kind":"identifier","text":"AlltServerStateReady"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1playing\/title","value":"AlltServerStatePlaying","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1playing\/fragments","value":[{"text":"AlltServerStatePlaying","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1paused\/title","value":"AlltServerStatePaused","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1paused\/fragments","value":[{"text":"AlltServerStatePaused","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1offline\/title","value":"AlltServerStateOffline","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1offline\/fragments","value":[{"kind":"identifier","text":"AlltServerStateOffline"}],"op":"replace"}]}]}