{"abstract":[{"text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed","type":"text"}],"metadata":{"externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)didBecomeActive","required":true,"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didBecomeActive"}],"role":"symbol","modules":[{"name":"AlltKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeActive"},{"kind":"text","text":"()"}],"title":"didBecomeActive()","platforms":[],"symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeActive"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/didbecomeactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/didbecomeactive()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeActive()"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/didBecomeActive()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didBecomeActive","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didBecomeActive()","type":"topic","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/didbecomeactive()","kind":"symbol","role":"symbol","title":"didBecomeActive()","navigatorTitle":[{"kind":"identifier","text":"didBecomeActive"}],"required":true,"abstract":[{"type":"text","text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed"}],"deprecated":true},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"abstract":[],"title":"AlltMenuViewDelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"didBecomeActive","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didBecomeActive","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didBecomeActive"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeActive()\/title","value":"didBecomeActive"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didBecomeActive()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didBecomeActive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","op":"replace","value":"AlltMenuViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","value":[{"kind":"identifier","text":"AlltMenuViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}