{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateAlltContent"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/didupdatealltcontent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/didupdatealltcontent()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didUpdateAlltContent()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed"}],"kind":"symbol","metadata":{"modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"didUpdateAlltContent"}],"role":"symbol","title":"didUpdateAlltContent()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateAlltContent"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)didUpdateAlltContent","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"role":"collection","title":"AlltKit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","kind":"symbol","type":"topic","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/didUpdateAlltContent()":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateAlltContent"}],"deprecated":true,"role":"symbol","title":"didUpdateAlltContent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateAlltContent"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when Allt has discovered some currently playing content, or the currently playing content has changed"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/didUpdateAlltContent()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/didupdatealltcontent()"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"deprecated":true,"role":"symbol","title":"AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didUpdateAlltContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateAlltContent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateAlltContent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didUpdateAlltContent()\/title","value":"didUpdateAlltContent"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1didUpdateAlltContent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateAlltContent"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","value":"AlltMenuViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","value":[{"kind":"identifier","text":"AlltMenuViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}