{"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endAdvertizing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endAdvertizingWithIdentifier:"}],"externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)endAdvertizingWithIdentifier:","modules":[{"name":"AlltKit"}],"title":"endAdvertizing(identifier:)","symbolKind":"method","platforms":[],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/endadvertizing(identifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/endadvertizing(identifier:)"]}],"abstract":[{"text":"Called when allt-enabled advertizing has finished playing","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/endAdvertizing(identifier:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endAdvertizing"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"abstract":[],"title":"AlltMenuViewDelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate","type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/endAdvertizing(identifier:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/endAdvertizing(identifier:)","navigatorTitle":[{"text":"endAdvertizingWithIdentifier:","kind":"identifier"}],"role":"symbol","title":"endAdvertizing(identifier:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endAdvertizing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[{"text":"Called when allt-enabled advertizing has finished playing","type":"text"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate\/endadvertizing(identifier:)"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"endAdvertizingWithIdentifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"endAdvertizingWithIdentifier:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"endAdvertizingWithIdentifier:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"identifier","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","value":"AlltMenuViewDelegate"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"endAdvertizingWithIdentifier:","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1endAdvertizing(identifier:)\/title"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1endAdvertizing(identifier:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"endAdvertizingWithIdentifier:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}