{"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/receivedPosterURLs(small:large:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedPosterURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"small"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"large"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"receivedPosterURLsWithSmall:large:"}],"title":"receivedPosterURLs(small:large:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedPosterURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"small"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"large"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)receivedPosterURLsWithSmall:large:","role":"symbol"},"abstract":[{"type":"text","text":"Called when Allt has resolved the currently playing content, passing URLs for both small and large poster representations."}],"variants":[{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/receivedposterurls(small:large:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/receivedposterurls(small:large:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate","title":"AlltMenuViewDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[{"type":"text","text":"Delegate interface for AlltMenuView"}],"type":"topic","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/receivedPosterURLs(small:large:)":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/receivedPosterURLs(small:large:)","abstract":[{"text":"Called when Allt has resolved the currently playing content, passing URLs for both small and large poster representations.","type":"text"}],"role":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/receivedposterurls(small:large:)","kind":"symbol","type":"topic","title":"receivedPosterURLs(small:large:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receivedPosterURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"small","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"large","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"receivedPosterURLsWithSmall:large:","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"receivedPosterURLsWithSmall:large:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"receivedPosterURLsWithSmall:large:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"receivedPosterURLsWithSmall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"small"},{"kind":"text","text":" "},{"kind":"identifier","text":"large:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"large"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AlltMenuViewDelegate","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title"},{"value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments"},{"value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/navigatorTitle"},{"value":"receivedPosterURLsWithSmall:large:","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1receivedPosterURLs(small:large:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"receivedPosterURLsWithSmall:large:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1receivedPosterURLs(small:large:)\/fragments"}]}]}