{"kind":"symbol","metadata":{"modules":[{"name":"AlltKit"}],"navigatorTitle":[{"text":"showInteractiveAdvertizingWithAdURL:","kind":"identifier"}],"title":"showInteractiveAdvertizing(adURL:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showInteractiveAdvertizing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)showInteractiveAdvertizingWithAdURL:","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showInteractiveAdvertizing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Called when allt-enabled advertizing is playing on the server"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showInteractiveAdvertizing(adURL:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/showinteractiveadvertizing(adurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/showinteractiveadvertizing(adurl:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate","title":"AlltMenuViewDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[{"type":"text","text":"Delegate interface for AlltMenuView"}],"type":"topic","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/showInteractiveAdvertizing(adURL:)":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showInteractiveAdvertizing(adURL:)","abstract":[{"type":"text","text":"Called when allt-enabled advertizing is playing on the server"}],"role":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/showinteractiveadvertizing(adurl:)","kind":"symbol","type":"topic","title":"showInteractiveAdvertizing(adURL:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showInteractiveAdvertizing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"showInteractiveAdvertizingWithAdURL:","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"showInteractiveAdvertizingWithAdURL:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showInteractiveAdvertizingWithAdURL:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"showInteractiveAdvertizingWithAdURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"adURL","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","op":"replace","value":"AlltMenuViewDelegate"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","op":"replace","value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}]},{"value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showInteractiveAdvertizing(adURL:)\/title","op":"replace","value":"showInteractiveAdvertizingWithAdURL:"},{"value":[{"kind":"text","text":"- "},{"text":"showInteractiveAdvertizingWithAdURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showInteractiveAdvertizing(adURL:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}