{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAdvertizing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onClickURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/showadvertizing(identifier:onclickurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltmenuviewdelegate\/showadvertizing(identifier:onclickurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showAdvertizing(identifier:onClickURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when allt-enabled advertizing is playing on the server"}],"kind":"symbol","metadata":{"modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"showAdvertizingWithIdentifier:onClickURL:"}],"role":"symbol","title":"showAdvertizing(identifier:onClickURL:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAdvertizing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onClickURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate(im)showAdvertizingWithIdentifier:onClickURL:","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate/showAdvertizing(identifier:onClickURL:)":{"navigatorTitle":[{"kind":"identifier","text":"showAdvertizingWithIdentifier:onClickURL:"}],"deprecated":true,"role":"symbol","title":"showAdvertizing(identifier:onClickURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAdvertizing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onClickURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when allt-enabled advertizing is playing on the server"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate\/showAdvertizing(identifier:onClickURL:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/alltkit\/alltmenuviewdelegate\/showadvertizing(identifier:onclickurl:)"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"role":"collection","title":"AlltKit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","kind":"symbol","type":"topic","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"deprecated":true,"role":"symbol","title":"AlltMenuViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showAdvertizingWithIdentifier:onClickURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAdvertizingWithIdentifier:onClickURL:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAdvertizingWithIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"onClickURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showAdvertizing(identifier:onClickURL:)\/title","value":"showAdvertizingWithIdentifier:onClickURL:"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate~1showAdvertizing(identifier:onClickURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAdvertizingWithIdentifier:onClickURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","value":"AlltMenuViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","value":[{"kind":"identifier","text":"AlltMenuViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}