{"sections":[],"abstract":[{"type":"text","text":"The "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" for the "},{"code":"AlltMenuView","type":"codeVoice"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"title":"delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AlltMenuViewDelegate","preciseIdentifier":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate"},{"kind":"text","text":"?"}],"modules":[{"name":"AlltKit"}],"externalID":"s:7AlltKit0A8MenuViewC8delegateAA0acD8Delegate_pSgvp","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/delegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","text":"AlltMenuViewDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/alltkit\/alltmenuview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/delegate":{"role":"symbol","title":"delegate","url":"\/documentation\/alltkit\/alltmenuview\/delegate","type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AlltKit@objc(pl)AlltMenuViewDelegate","kind":"typeIdentifier","text":"AlltMenuViewDelegate"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"delegate"},{"text":" for the ","type":"text"},{"type":"codeVoice","code":"AlltMenuView"}],"kind":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"title":"AlltMenuView","kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","url":"\/documentation\/alltkit\/alltmenuview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltMenuView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" properties.  The ","type":"text"},{"code":"presentingViewController","type":"codeVoice"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"type":"codeVoice","code":"showHistory"},{"type":"text","text":" and "},{"type":"codeVoice","code":"showSearch"},{"type":"text","text":" "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":"s to appropriate buttons in your User Interface."}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","url":"\/documentation\/alltkit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"kind":"symbol","title":"AlltKit","role":"collection"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"deprecated":true,"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","title":"AlltMenuViewDelegate","role":"symbol","url":"\/documentation\/alltkit\/alltmenuviewdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AlltMenuView","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"kind":"identifier","text":"AlltMenuView"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","op":"replace","value":"AlltMenuViewDelegate"},{"value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments"}]}]}