{"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/alltkit\/alltmenuview\/finishpopulatingwheel()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishPopulatingWheel"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/finishPopulatingWheel()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finishPopulatingWheel","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"AlltKit"}],"role":"symbol","title":"finishPopulatingWheel()","externalID":"s:7AlltKit0A8MenuViewC21finishPopulatingWheelyyF","roleHeading":"Instance Method"},"abstract":[{"text":"Call this function when the user has finished interacting with manually populated data.","type":"text"}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/finishPopulatingWheel()":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/finishPopulatingWheel()","abstract":[{"type":"text","text":"Call this function when the user has finished interacting with manually populated data."}],"role":"symbol","url":"\/documentation\/alltkit\/alltmenuview\/finishpopulatingwheel()","kind":"symbol","type":"topic","title":"finishPopulatingWheel()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finishPopulatingWheel","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AlltMenuView","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title"},{"op":"replace","value":[{"text":"AlltMenuView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments"},{"op":"replace","value":[{"text":"AlltMenuView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle"}]}]}