{"metadata":{"externalID":"c:@M@AlltKit@objc(cs)AlltMenuView(im)layoutSubviews","symbolKind":"method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"title":"layoutSubviews()","role":"symbol","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltmenuview\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuview\/layoutsubviews()"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/layoutSubviews()"},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/layoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/layoutSubviews()","url":"\/documentation\/alltkit\/alltmenuview\/layoutsubviews()"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"layoutSubviews","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","value":"AlltMenuView","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"text":"AlltMenuView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle","value":[{"kind":"identifier","text":"AlltMenuView"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}