{"variants":[{"paths":["\/documentation\/alltkit\/alltmenuview\/point(inside:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltmenuview\/point(inside:with:)"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"point(inside:with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"point"},{"kind":"text","text":"("},{"text":"inside","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pointInside:withEvent:","kind":"identifier"}],"externalID":"c:@M@AlltKit@objc(cs)AlltMenuView(im)pointInside:withEvent:","modules":[{"name":"AlltKit"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"point","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inside","kind":"externalParam"},{"kind":"text","text":" "},{"text":"point","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/point(inside:with:)","interfaceLanguage":"swift"},"abstract":[{"text":"Pass through any touch events that aren’t touching visible parts of our UI","type":"text"}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"title":"AlltMenuView","kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","url":"\/documentation\/alltkit\/alltmenuview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltMenuView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" properties.  The ","type":"text"},{"code":"presentingViewController","type":"codeVoice"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"type":"codeVoice","code":"showHistory"},{"type":"text","text":" and "},{"type":"codeVoice","code":"showSearch"},{"type":"text","text":" "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":"s to appropriate buttons in your User Interface."}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/point(inside:with:)":{"role":"symbol","title":"point(inside:with:)","url":"\/documentation\/alltkit\/alltmenuview\/point(inside:with:)","type":"topic","navigatorTitle":[{"text":"pointInside:withEvent:","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/point(inside:with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"point"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inside"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Pass through any touch events that aren’t touching visible parts of our UI"}],"kind":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","url":"\/documentation\/alltkit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"kind":"symbol","title":"AlltKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pointInside:withEvent:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pointInside:withEvent:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"pointInside:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withEvent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","op":"replace","value":"AlltMenuView"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"text":"AlltMenuView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1point(inside:with:)\/title","op":"replace","value":"pointInside:withEvent:"},{"value":[{"text":"- ","kind":"text"},{"text":"pointInside:withEvent:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1point(inside:with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}