{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"populateWheeel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAlltCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"alltCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaType","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaType","preciseIdentifier":"s:7AlltKit9MediaTypeO"},{"kind":"text","text":", "},{"text":"platform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"abstract":[{"text":"Call this function to manually populate the UI with information for the content represented by the ","type":"text"},{"type":"codeVoice","code":"alltCode"},{"text":" parameter","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/populateWheeel(forAlltCode:type:platform:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"populateWheeel"},{"text":"(","kind":"text"},{"text":"forAlltCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MediaType","kind":"typeIdentifier","preciseIdentifier":"s:7AlltKit9MediaTypeO"},{"text":", ","kind":"text"},{"text":"platform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"s:7AlltKit0A8MenuViewC14populateWheeel03forA4Code4type8platformySS_AA9MediaTypeOSSSgtF","title":"populateWheeel(forAlltCode:type:platform:)","symbolKind":"method","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltmenuview\/populatewheeel(foralltcode:type:platform:)"]}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/populateWheeel(forAlltCode:type:platform:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"populateWheeel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAlltCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MediaType","kind":"typeIdentifier","preciseIdentifier":"s:7AlltKit9MediaTypeO"},{"text":", ","kind":"text"},{"text":"platform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/alltkit\/alltmenuview\/populatewheeel(foralltcode:type:platform:)","abstract":[{"text":"Call this function to manually populate the UI with information for the content represented by the ","type":"text"},{"type":"codeVoice","code":"alltCode"},{"text":" parameter","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/populateWheeel(forAlltCode:type:platform:)","title":"populateWheeel(forAlltCode:type:platform:)","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/MediaType":{"url":"\/documentation\/alltkit\/mediatype","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaType","title":"MediaType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MediaType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaType"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","value":"AlltMenuView"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"text":"AlltMenuView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle","value":[{"kind":"identifier","text":"AlltMenuView"}]}]}]}