{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reset","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"metadata":{"externalID":"s:7AlltKit0A8MenuViewC5resetyyF","symbolKind":"method","title":"reset()","role":"symbol","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"()"}]},"kind":"symbol","abstract":[{"type":"text","text":"Reset the "},{"code":"AlltMenuView","type":"codeVoice"},{"type":"text","text":" data source"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/reset()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/alltkit\/alltmenuview\/reset()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/reset()":{"title":"reset()","abstract":[{"text":"Reset the ","type":"text"},{"code":"AlltMenuView","type":"codeVoice"},{"text":" data source","type":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/reset()","role":"symbol","url":"\/documentation\/alltkit\/alltmenuview\/reset()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"()"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AlltMenuView","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AlltMenuView"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","op":"replace"},{"value":[{"text":"AlltMenuView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle","op":"replace"}]}]}