{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltmenuview\/showhistory(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltmenuview\/showhistory(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/showHistory(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connect this "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":" to a suitable button in your UI.  AlltKit will create and present a ViewController to display and interact with the user’s allt history."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showHistory"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"title":"showHistory(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AlltKit@objc(cs)AlltMenuView(im)showHistory:","modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"showHistory:"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"role":"symbol","title":"AlltMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuView"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"type":"codeVoice","code":"showHistory"},{"type":"text","text":" and "},{"type":"codeVoice","code":"showSearch"},{"type":"text","text":" "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":"s to appropriate buttons in your User Interface."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltMenuView"}],"url":"\/documentation\/alltkit\/alltmenuview"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/showHistory(_:)":{"role":"symbol","title":"showHistory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showHistory"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Connect this "},{"type":"codeVoice","code":"IBAction"},{"type":"text","text":" to a suitable button in your UI.  AlltKit will create and present a ViewController to display and interact with the user’s allt history."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/showHistory(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showHistory:"}],"url":"\/documentation\/alltkit\/alltmenuview\/showhistory(_:)"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"role":"collection","title":"AlltKit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","kind":"symbol","type":"topic","url":"\/documentation\/alltkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showHistory:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showHistory:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showHistory:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","value":"AlltMenuView"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"kind":"identifier","text":"AlltMenuView"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1showHistory(_:)\/title","value":"showHistory:"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView~1showHistory(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showHistory:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}