{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInteractedWithAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:7AlltKit0A8MenuViewC20userInteractedWithAd3urlySS_tF","symbolKind":"method","title":"userInteractedWithAd(url:)","role":"symbol","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userInteractedWithAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltmenuview\/userinteractedwithad(url:)"]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/userInteractedWithAd(url:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView/userInteractedWithAd(url:)":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView\/userInteractedWithAd(url:)","url":"\/documentation\/alltkit\/alltmenuview\/userinteractedwithad(url:)","title":"userInteractedWithAd(url:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInteractedWithAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title","value":"AlltMenuView","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments","value":[{"kind":"identifier","text":"AlltMenuView"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle","value":[{"kind":"identifier","text":"AlltMenuView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}