{"metadata":{"title":"alltCodeMediaType","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alltCodeMediaType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"s:7AlltKit0A16ServerConnectionC17alltCodeMediaTypeSSSgvp"},"variants":[{"paths":["\/documentation\/alltkit\/alltserverconnection\/alltcodemediatype"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alltCodeMediaType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection"]]},"kind":"symbol","identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/alltCodeMediaType","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"type":"codeVoice","code":"AlltServer"},{"type":"text","text":".  The "},{"type":"codeVoice","code":"currentAlltCode"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/alltCodeMediaType":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/alltCodeMediaType","abstract":[],"role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection\/alltcodemediatype","kind":"symbol","type":"topic","title":"alltCodeMediaType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alltCodeMediaType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","value":"AlltServerConnection"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","value":[{"text":"AlltServerConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/navigatorTitle","value":[{"text":"AlltServerConnection","kind":"identifier"}]}]}]}