{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playbackState","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState","text":"AlltServerState","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/playbackState","interfaceLanguage":"swift"},"abstract":[{"text":"Current playback state","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltserverconnection\/playbackstate"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","title":"playbackState","symbolKind":"property","modules":[{"name":"AlltKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AlltServerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState"},{"text":"?","kind":"text"}],"externalID":"s:7AlltKit0A16ServerConnectionC13playbackStateAA0acF0OSgvp"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"url":"\/documentation\/alltkit\/alltserverstate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","url":"\/documentation\/alltkit\/alltserverconnection","role":"symbol","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"code":"AlltServer","type":"codeVoice"},{"type":"text","text":".  The "},{"code":"currentAlltCode","type":"codeVoice"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection/playbackState":{"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection\/playbackState","abstract":[{"text":"Current playback state","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AlltServerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState"},{"text":"?","kind":"text"}],"url":"\/documentation\/alltkit\/alltserverconnection\/playbackstate","role":"symbol","title":"playbackState","type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AlltServerState","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"text":"AlltServerState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","value":"AlltServerConnection"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","value":[{"text":"AlltServerConnection","kind":"identifier"}]}]}]}