{"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/clientDidUnsubscribe(uuid:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientDidUnsubscribe"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uuid"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"clientDidUnsubscribe(uuid:)","navigatorTitle":[{"kind":"identifier","text":"clientDidUnsubscribeWithUuid:"}],"modules":[{"name":"AlltKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientDidUnsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@AlltKit@objc(pl)AlltServerDelegate(im)clientDidUnsubscribeWithUuid:"},"abstract":[{"text":"Called when a client has subscribed to our server.  Return value allows the Media Player to target updates to individual clients.  Return true to allow the client to receive events, and false to disallow them.  The client will not be aware that it will not be receiving events.","type":"text"}],"variants":[{"paths":["\/documentation\/alltkit\/alltserverdelegate\/clientdidunsubscribe(uuid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverdelegate\/clientdidunsubscribe(uuid:)"]}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate":{"title":"AlltServerDelegate","navigatorTitle":[{"text":"AlltServerDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate callbacks for the AlltServer object, providing updates on client status, network connection status, and server state.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerDelegate","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate/clientDidUnsubscribe(uuid:)":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/clientDidUnsubscribe(uuid:)","navigatorTitle":[{"text":"clientDidUnsubscribeWithUuid:","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltserverdelegate\/clientdidunsubscribe(uuid:)","title":"clientDidUnsubscribe(uuid:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clientDidUnsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uuid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when a client has subscribed to our server.  Return value allows the Media Player to target updates to individual clients.  Return true to allow the client to receive events, and false to disallow them.  The client will not be aware that it will not be receiving events."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"clientDidUnsubscribeWithUuid:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"clientDidUnsubscribeWithUuid:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"clientDidUnsubscribeWithUuid:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uuid"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AlltServerDelegate","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/title"},{"value":[{"text":"AlltServerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/fragments"},{"value":[{"text":"AlltServerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/navigatorTitle"},{"value":"clientDidUnsubscribeWithUuid:","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1clientDidUnsubscribe(uuid:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"clientDidUnsubscribeWithUuid:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1clientDidUnsubscribe(uuid:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}