{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnected"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltserverdelegate\/networkconnected()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltserverdelegate\/networkconnected()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/networkConnected()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the underlying network between clients and our server is ready"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnected"},{"kind":"text","text":"()"}],"title":"networkConnected()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AlltKit@objc(pl)AlltServerDelegate(im)networkConnected","modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"networkConnected"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"role":"collection","title":"AlltKit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","kind":"symbol","type":"topic","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate":{"role":"symbol","title":"AlltServerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerDelegate"}],"abstract":[{"type":"text","text":"Delegate callbacks for the AlltServer object, providing updates on client status, network connection status, and server state."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerDelegate"}],"url":"\/documentation\/alltkit\/alltserverdelegate"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate/networkConnected()":{"role":"symbol","title":"networkConnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the underlying network between clients and our server is ready"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/networkConnected()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkConnected"}],"url":"\/documentation\/alltkit\/alltserverdelegate\/networkconnected()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"networkConnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"networkConnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"networkConnected"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/title","value":"AlltServerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/fragments","value":[{"kind":"identifier","text":"AlltServerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1networkConnected()\/title","value":"networkConnected"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1networkConnected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"networkConnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}