{"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AlltKit@objc(pl)AlltServerDelegate(im)serverStateChangedWithState:","title":"serverStateChanged(state:)","navigatorTitle":[{"kind":"identifier","text":"serverStateChangedWithState:"}],"required":true,"modules":[{"name":"AlltKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"state","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AlltKit@E@AlltServerState","text":"AlltServerState","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Called whenever the state of our server has changed"}],"variants":[{"paths":["\/documentation\/alltkit\/alltserverdelegate\/serverstatechanged(state:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverdelegate\/serverstatechanged(state:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/serverStateChanged(state:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"text":"AlltServerState","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","url":"\/documentation\/alltkit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"kind":"symbol","title":"AlltKit","role":"collection"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate":{"abstract":[{"text":"Delegate callbacks for the AlltServer object, providing updates on client status, network connection status, and server state.","type":"text"}],"kind":"symbol","title":"AlltServerDelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltServerDelegate","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltServerDelegate"}],"url":"\/documentation\/alltkit\/alltserverdelegate"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerState"}],"navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"url":"\/documentation\/alltkit\/alltserverstate","role":"symbol","type":"topic","kind":"symbol","title":"AlltServerState","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","abstract":[{"type":"text","text":"Enumerates the possible states of the AlltServer"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate/serverStateChanged(state:)":{"url":"\/documentation\/alltkit\/alltserverdelegate\/serverstatechanged(state:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"serverStateChangedWithState:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"serverStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"state","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AlltServerState","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called whenever the state of our server has changed"}],"required":true,"title":"serverStateChanged(state:)","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/serverStateChanged(state:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"serverStateChangedWithState:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serverStateChangedWithState:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"serverStateChangedWithState:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","preciseIdentifier":"c:@M@AlltKit@E@AlltServerState","text":"AlltServerState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/title","value":"AlltServerDelegate"},{"value":[{"kind":"identifier","text":"AlltServerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","value":"AlltServerState"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"kind":"identifier","text":"AlltServerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1serverStateChanged(state:)\/title","op":"replace","value":"serverStateChangedWithState:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"serverStateChangedWithState:"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1serverStateChanged(state:)\/fragments"}]}]}