{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"subscriberDidInteractWithAd"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriberDidInteractWithAd"},{"kind":"text","text":"()"}],"modules":[{"name":"AlltKit"}],"title":"subscriberDidInteractWithAd()","role":"symbol","externalID":"c:@M@AlltKit@objc(pl)AlltServerDelegate(im)subscriberDidInteractWithAd","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriberDidInteractWithAd"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"Called whenever the state of our server has changed","type":"text"}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/subscriberDidInteractWithAd()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltserverdelegate\/subscriberdidinteractwithad()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverdelegate\/subscriberdidinteractwithad()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate":{"title":"AlltServerDelegate","navigatorTitle":[{"text":"AlltServerDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate callbacks for the AlltServer object, providing updates on client status, network connection status, and server state.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerDelegate","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate/subscriberDidInteractWithAd()":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate\/subscriberDidInteractWithAd()","abstract":[{"type":"text","text":"Called whenever the state of our server has changed"}],"role":"symbol","url":"\/documentation\/alltkit\/alltserverdelegate\/subscriberdidinteractwithad()","kind":"symbol","type":"topic","title":"subscriberDidInteractWithAd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriberDidInteractWithAd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"subscriberDidInteractWithAd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"subscriberDidInteractWithAd","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscriberDidInteractWithAd"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"subscriberDidInteractWithAd"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"AlltServerDelegate","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AlltServerDelegate"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/fragments"},{"op":"replace","value":[{"text":"AlltServerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/navigatorTitle"},{"op":"replace","value":"subscriberDidInteractWithAd","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1subscriberDidInteractWithAd()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subscriberDidInteractWithAd","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate~1subscriberDidInteractWithAd()\/fragments"}]}]}