{"variants":[{"paths":["\/documentation\/alltkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Initial Documentation Release. Contact your Allt representative for questions \/ integration help."}]},{"type":"paragraph","inlineContent":[{"text":"N.B. This release includes BLE as an alternative to broadcast Allt codes. Your application will require the ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"text":" key ‘Privacy - Bluetooth Always Usage Description’ to be set.","type":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collection","modules":[{"name":"AlltKit"}],"title":"AlltKit","roleHeading":"Framework","externalID":"AlltKit","symbolKind":"module"},"abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClient","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServer","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/CreditPerson","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworks","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageCollection","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaItem","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/NetworkEntity","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/NetworkEntityAction","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ProductionCompany"]},{"generated":true,"title":"Protocols","anchor":"Protocols","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"]},{"generated":true,"title":"Structures","anchor":"Structures","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/Credit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageReference"]},{"generated":true,"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/TTVDbShowID"]},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/CreditType","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworkType","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalSource","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageReferenceSize","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaType"]},{"generated":true,"title":"Extended Modules","anchor":"Extended-Modules","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/Foundation"]}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServer","kind":"identifier"}],"navigatorTitle":[{"text":"AlltServer","kind":"identifier"}],"title":"AlltServer","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Exposes API for allt server implementation for media players","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServer","url":"\/documentation\/alltkit\/alltserver"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltKitVersionString":{"role":"symbol","url":"\/documentation\/alltkit\/alltkitversionstring","type":"topic","fragments":[{"text":"AlltKitVersionString","kind":"identifier"}],"kind":"symbol","title":"AlltKitVersionString","abstract":[{"type":"text","text":"Project version string for AlltKit."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltKitVersionString"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClient":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClient","abstract":[{"type":"text","text":"Exposes API for implementing an Allt Client, receiving Allt-code updates from AlltServers on the local network"}],"role":"symbol","url":"\/documentation\/alltkit\/alltclient","kind":"symbol","type":"topic","title":"AlltClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlltClient"}],"navigatorTitle":[{"kind":"identifier","text":"AlltClient"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/NetworkEntity":{"role":"symbol","url":"\/documentation\/alltkit\/networkentity","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkEntity","kind":"identifier"}],"kind":"symbol","title":"NetworkEntity","navigatorTitle":[{"text":"NetworkEntity","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/NetworkEntity","abstract":[]},"doc://tv.allt.AlltKit/documentation/AlltKit/Credit":{"navigatorTitle":[{"text":"Credit","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Credit"}],"type":"topic","url":"\/documentation\/alltkit\/credit","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/Credit","title":"Credit","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/CreditPerson":{"url":"\/documentation\/alltkit\/creditperson","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"CreditPerson","kind":"identifier"}],"title":"CreditPerson","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/CreditPerson","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreditPerson","kind":"identifier"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/ExternalSource":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalSource","navigatorTitle":[{"kind":"identifier","text":"ExternalSource"}],"url":"\/documentation\/alltkit\/externalsource","title":"ExternalSource","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExternalSource","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/CreditType":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/CreditType","abstract":[],"role":"symbol","url":"\/documentation\/alltkit\/credittype","kind":"symbol","type":"topic","title":"CreditType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreditType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreditType"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerDelegate":{"title":"AlltServerDelegate","navigatorTitle":[{"text":"AlltServerDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate callbacks for the AlltServer object, providing updates on client status, network connection status, and server state.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerDelegate","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/ProductionCompany":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductionCompany"}],"navigatorTitle":[{"kind":"identifier","text":"ProductionCompany"}],"title":"ProductionCompany","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ProductionCompany","url":"\/documentation\/alltkit\/productioncompany"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltActionMenuView":{"title":"AlltActionMenuView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AlltActionMenuView","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltactionmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","abstract":[{"text":"User Interface component for Allt, specific to one External Network action type.   Drop this into your view hierarchy and set the ","type":"text"},{"code":"delegate","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" properties.  The ","type":"text"},{"type":"codeVoice","code":"presentingViewController"},{"text":" property is used to push the modal Allt User Interface.  Connect the ","type":"text"},{"type":"codeVoice","code":"showHistory"},{"text":" and ","type":"text"},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AlltActionMenuView","kind":"identifier"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltKitVersionNumber":{"role":"symbol","url":"\/documentation\/alltkit\/alltkitversionnumber","type":"topic","fragments":[{"text":"AlltKitVersionNumber","kind":"identifier"}],"kind":"symbol","title":"AlltKitVersionNumber","abstract":[{"text":"Project version number for AlltKit.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltKitVersionNumber"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClientDelegate":{"role":"symbol","url":"\/documentation\/alltkit\/alltclientdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltClientDelegate"}],"kind":"symbol","title":"AlltClientDelegate","navigatorTitle":[{"kind":"identifier","text":"AlltClientDelegate"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate"},"doc://tv.allt.AlltKit/documentation/AlltKit/Foundation":{"role":"collection","url":"\/documentation\/alltkit\/foundation","type":"topic","kind":"symbol","title":"Foundation","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/Foundation"},"doc://tv.allt.AlltKit/documentation/AlltKit/TTVDbShowID":{"title":"TTVDbShowID","navigatorTitle":[{"text":"TTVDbShowID","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/TTVDbShowID","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/ttvdbshowid","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TTVDbShowID","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuView":{"kind":"symbol","url":"\/documentation\/alltkit\/alltmenuview","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlltMenuView","kind":"identifier"}],"abstract":[{"type":"text","text":"User Interface component for Allt - drop this into your view hierarchy and set the "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" properties.  The "},{"type":"codeVoice","code":"presentingViewController"},{"type":"text","text":" property is used to push the modal Allt User Interface.  Connect the "},{"code":"showHistory","type":"codeVoice"},{"type":"text","text":" and "},{"code":"showSearch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IBAction"},{"text":"s to appropriate buttons in your User Interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltMenuView","kind":"identifier"}],"title":"AlltMenuView"},"doc://tv.allt.AlltKit/documentation/AlltKit/NetworkEntityAction":{"url":"\/documentation\/alltkit\/networkentityaction","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"NetworkEntityAction","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/NetworkEntityAction","title":"NetworkEntityAction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkEntityAction"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/ImageReference":{"navigatorTitle":[{"text":"ImageReference","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ImageReference","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/alltkit\/imagereference","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageReference","title":"ImageReference","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/ImageReferenceSize":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageReferenceSize","abstract":[],"role":"symbol","url":"\/documentation\/alltkit\/imagereferencesize","kind":"symbol","type":"topic","title":"ImageReferenceSize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageReferenceSize","kind":"identifier"}],"navigatorTitle":[{"text":"ImageReferenceSize","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/MediaType":{"url":"\/documentation\/alltkit\/mediatype","role":"symbol","abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaType","title":"MediaType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MediaType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaType"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/ImageCollection":{"title":"ImageCollection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageCollection","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ImageCollection","url":"\/documentation\/alltkit\/imagecollection","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ImageCollection","kind":"identifier"}],"type":"topic"},"doc://tv.allt.AlltKit/documentation/AlltKit/ExternalNetworkType":{"url":"\/documentation\/alltkit\/externalnetworktype","kind":"symbol","title":"ExternalNetworkType","navigatorTitle":[{"kind":"identifier","text":"ExternalNetworkType"}],"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ExternalNetworkType","kind":"identifier"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworkType"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","navigatorTitle":[{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverstate","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerState","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/MediaItem":{"title":"MediaItem","navigatorTitle":[{"text":"MediaItem","kind":"identifier"}],"abstract":[{"text":"Changed to using a raw string rather than an enum, since the ViewingPlatforms are server controlled and can be updated on the fly","type":"text"},{"text":" ","type":"text"},{"text":"If we stick with an enum we have to re-issue the SDK every time a ViewingPlatform is added\/removed, which makes no sense.  The backend API call can fail if the provided platform is incorrect, and this is the correct behavior.","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/MediaItem","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/mediaitem","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaItem","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/ExternalNetworks":{"title":"ExternalNetworks","navigatorTitle":[{"text":"ExternalNetworks","kind":"identifier"}],"abstract":[{"text":"Represents the holistic media profiles for a ","type":"text"},{"type":"codeVoice","code":"CastMember"},{"type":"text","text":" or "},{"type":"codeVoice","code":"MediaItem"},{"type":"text","text":" including any hashtags that "},{"type":"emphasis","inlineContent":[{"type":"text","text":"may"}]},{"type":"text","text":" be associated"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/ExternalNetworks","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/externalnetworks","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ExternalNetworks","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltMenuViewDelegate":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","navigatorTitle":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"url":"\/documentation\/alltkit\/alltmenuviewdelegate","title":"AlltMenuViewDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltMenuViewDelegate"}],"abstract":[{"type":"text","text":"Delegate interface for AlltMenuView"}],"type":"topic","role":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"type":"codeVoice","code":"AlltServer"},{"type":"text","text":".  The "},{"type":"codeVoice","code":"currentAlltCode"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltActionMenuView","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuView","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection"],"generated":true},{"anchor":"Protocols","title":"Protocols","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltMenuViewDelegate","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerDelegate"],"generated":true},{"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltKitVersionNumber","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltKitVersionString"],"generated":true},{"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"],"generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"AlltServerDelegate","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/title"},{"op":"replace","value":[{"text":"AlltServerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/fragments"},{"op":"replace","value":[{"text":"AlltServerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerDelegate\/navigatorTitle"},{"op":"replace","value":"AlltActionMenuView","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AlltActionMenuView"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AlltActionMenuView"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltActionMenuView\/navigatorTitle"},{"op":"replace","value":"AlltClientDelegate","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/title"},{"op":"replace","value":[{"text":"AlltClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AlltClientDelegate"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/navigatorTitle"},{"op":"replace","value":"AlltMenuView","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/title"},{"op":"replace","value":[{"text":"AlltMenuView","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/fragments"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AlltMenuView"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","op":"replace","value":"AlltServerState"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"kind":"identifier","text":"AlltServerState"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/navigatorTitle","value":[{"text":"AlltServerState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/title","value":"AlltMenuViewDelegate"},{"value":[{"text":"AlltMenuViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AlltMenuViewDelegate"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltMenuViewDelegate\/navigatorTitle","op":"replace"},{"value":"AlltServerConnection","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","op":"replace"},{"value":[{"text":"AlltServerConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/navigatorTitle","value":[{"text":"AlltServerConnection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}