{"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate\/serverSubscribed(connection:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverSubscribed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AlltServerConnection","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltclientdelegate\/serversubscribed(connection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltclientdelegate\/serversubscribed(connection:)"]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"AlltKit"}],"role":"symbol","externalID":"c:@M@AlltKit@objc(pl)AlltClientDelegate(im)serverSubscribedWithConnection:","title":"serverSubscribed(connection:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverSubscribed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection","kind":"typeIdentifier","text":"AlltServerConnection"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"serverSubscribedWithConnection:","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"type":"codeVoice","code":"AlltServer"},{"type":"text","text":".  The "},{"type":"codeVoice","code":"currentAlltCode"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","role":"symbol","url":"\/documentation\/alltkit\/alltserverconnection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClientDelegate":{"role":"symbol","url":"\/documentation\/alltkit\/alltclientdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltClientDelegate"}],"kind":"symbol","title":"AlltClientDelegate","navigatorTitle":[{"kind":"identifier","text":"AlltClientDelegate"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClientDelegate/serverSubscribed(connection:)":{"title":"serverSubscribed(connection:)","navigatorTitle":[{"text":"serverSubscribedWithConnection:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate\/serverSubscribed(connection:)","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltclientdelegate\/serversubscribed(connection:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverSubscribed"},{"kind":"text","text":"("},{"text":"connection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AlltServerConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"serverSubscribedWithConnection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serverSubscribedWithConnection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"serverSubscribedWithConnection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AlltServerConnection","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection","kind":"typeIdentifier","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection"},{"text":" *) ","kind":"text"},{"text":"connection","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","value":"AlltServerConnection"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","value":[{"text":"AlltServerConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/navigatorTitle","value":[{"text":"AlltServerConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/title","value":"AlltClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/fragments","value":[{"kind":"identifier","text":"AlltClientDelegate"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AlltClientDelegate"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate~1serverSubscribed(connection:)\/title","op":"replace","value":"serverSubscribedWithConnection:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"serverSubscribedWithConnection:","kind":"identifier"}],"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate~1serverSubscribed(connection:)\/fragments"}]}]}