{"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate\/serverUnsubscribed(connection:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverUnsubscribed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AlltServerConnection","kind":"typeIdentifier","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/alltkit\/alltclientdelegate\/serverunsubscribed(connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltclientdelegate\/serverunsubscribed(connection:)"]}],"metadata":{"title":"serverUnsubscribed(connection:)","role":"symbol","required":true,"externalID":"c:@M@AlltKit@objc(pl)AlltClientDelegate(im)serverUnsubscribedWithConnection:","modules":[{"name":"AlltKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverUnsubscribed","kind":"identifier"},{"kind":"text","text":"("},{"text":"connection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AlltServerConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"serverUnsubscribedWithConnection:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate"]]},"kind":"symbol","references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerConnection":{"title":"AlltServerConnection","url":"\/documentation\/alltkit\/alltserverconnection","role":"symbol","navigatorTitle":[{"text":"AlltServerConnection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AlltServerConnection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"AlltServerConnection"},{"type":"text","text":" object provides content playback information for a specific "},{"code":"AlltServer","type":"codeVoice"},{"type":"text","text":".  The "},{"code":"currentAlltCode","type":"codeVoice"},{"type":"text","text":" published parameter pushes updates whenever the currently playing content (or content state) changes."}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClientDelegate":{"role":"symbol","url":"\/documentation\/alltkit\/alltclientdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AlltClientDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AlltClientDelegate"}],"abstract":[],"type":"topic","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate","title":"AlltClientDelegate","kind":"symbol"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltClientDelegate/serverUnsubscribed(connection:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"serverUnsubscribed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"connection"},{"text":": ","kind":"text"},{"text":"AlltServerConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltClientDelegate\/serverUnsubscribed(connection:)","role":"symbol","navigatorTitle":[{"text":"serverUnsubscribedWithConnection:","kind":"identifier"}],"type":"topic","abstract":[],"title":"serverUnsubscribed(connection:)","url":"\/documentation\/alltkit\/alltclientdelegate\/serverunsubscribed(connection:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"serverUnsubscribedWithConnection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"serverUnsubscribedWithConnection:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"serverUnsubscribedWithConnection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AlltKit@objc(cs)AlltServerConnection","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerConnection","text":"AlltServerConnection"},{"kind":"text","text":" *) "},{"text":"connection","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AlltServerConnection","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerConnection\/fragments","value":[{"kind":"identifier","text":"AlltServerConnection"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/title","value":"AlltClientDelegate","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate\/fragments","op":"replace","value":[{"text":"AlltClientDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate~1serverUnsubscribed(connection:)\/title","value":"serverUnsubscribedWithConnection:","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltClientDelegate~1serverUnsubscribed(connection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"serverUnsubscribedWithConnection:","kind":"identifier"}],"op":"replace"}]}]}