{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/offline"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offline"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltserverstate\/offline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverstate\/offline"]}],"kind":"symbol","metadata":{"modules":[{"name":"AlltKit"}],"navigatorTitle":[{"text":"AlltServerStateOffline","kind":"identifier"}],"title":"AlltServerState.offline","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"role":"symbol","externalID":"c:@M@AlltKit@E@AlltServerState@AlltServerStateOffline"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","url":"\/documentation\/alltkit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","navigatorTitle":[{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","kind":"symbol","role":"symbol","url":"\/documentation\/alltkit\/alltserverstate","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlltServerState","kind":"identifier"}]},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/offline":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/offline","navigatorTitle":[{"text":"AlltServerStateOffline","kind":"identifier"}],"url":"\/documentation\/alltkit\/alltserverstate\/offline","title":"AlltServerState.offline","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AlltServerStateOffline","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AlltServerStateOffline","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AlltServerStateOffline","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","value":"AlltServerState","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/navigatorTitle","value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1offline\/title","value":"AlltServerStateOffline","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1offline\/fragments","value":[{"text":"AlltServerStateOffline","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}