{"abstract":[{"text":"The alltServer is  connected to a network but no media has been played","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"paused","kind":"identifier"}]}]}],"kind":"symbol","metadata":{"symbolKind":"case","title":"AlltServerState.paused","navigatorTitle":[{"kind":"identifier","text":"AlltServerStatePaused"}],"externalID":"c:@M@AlltKit@E@AlltServerState@AlltServerStatePaused","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paused"}],"modules":[{"name":"AlltKit"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltserverstate\/paused"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverstate\/paused"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/paused"},"sections":[],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/paused":{"title":"AlltServerState.paused","role":"symbol","navigatorTitle":[{"text":"AlltServerStatePaused","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"}],"abstract":[{"type":"text","text":"The alltServer is  connected to a network but no media has been played"}],"type":"topic","url":"\/documentation\/alltkit\/alltserverstate\/paused","kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/paused"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","type":"topic","url":"\/documentation\/alltkit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"kind":"symbol","title":"AlltKit","role":"collection"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerState"}],"navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"url":"\/documentation\/alltkit\/alltserverstate","role":"symbol","type":"topic","kind":"symbol","title":"AlltServerState","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","abstract":[{"type":"text","text":"Enumerates the possible states of the AlltServer"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"AlltServerStatePaused","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlltServerStatePaused"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AlltServerStatePaused"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1paused\/title","op":"replace","value":"AlltServerStatePaused"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1paused\/fragments","value":[{"text":"AlltServerStatePaused","kind":"identifier"}],"op":"replace"},{"value":"AlltServerState","op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title"},{"value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}