{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltserverstate\/playing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltserverstate\/playing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/playing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The alltServer is  connected to a network and media is currently paused"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"title":"AlltServerState.playing","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@AlltKit@E@AlltServerState@AlltServerStatePlaying","modules":[{"name":"AlltKit"}],"navigatorTitle":[{"kind":"identifier","text":"AlltServerStatePlaying"}]},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"]]},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/playing":{"role":"symbol","title":"AlltServerState.playing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"abstract":[{"type":"text","text":"The alltServer is  connected to a network and media is currently paused"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/playing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerStatePlaying"}],"url":"\/documentation\/alltkit\/alltserverstate\/playing"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"role":"symbol","title":"AlltServerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlltServerState"}],"abstract":[{"type":"text","text":"Enumerates the possible states of the AlltServer"}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"url":"\/documentation\/alltkit\/alltserverstate"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"role":"collection","title":"AlltKit","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","kind":"symbol","type":"topic","url":"\/documentation\/alltkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AlltServerStatePlaying"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlltServerStatePlaying"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AlltServerStatePlaying"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1playing\/title","value":"AlltServerStatePlaying"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1playing\/fragments","value":[{"kind":"identifier","text":"AlltServerStatePlaying"}]},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","value":"AlltServerState"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"kind":"identifier","text":"AlltServerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}