{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/ready","interfaceLanguage":"swift"},"abstract":[{"text":"The alltServer is not connected to a network","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ready"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/alltkit\/alltserverstate\/ready"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/alltkit\/alltserverstate\/ready"]}],"kind":"symbol","metadata":{"externalID":"c:@M@AlltKit@E@AlltServerState@AlltServerStateReady","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ready","kind":"identifier"}],"navigatorTitle":[{"text":"AlltServerStateReady","kind":"identifier"}],"title":"AlltServerState.ready","role":"symbol","roleHeading":"Case","modules":[{"name":"AlltKit"}],"symbolKind":"case"},"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"url":"\/documentation\/alltkit\/alltserverstate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/ready":{"navigatorTitle":[{"text":"AlltServerStateReady","kind":"identifier"}],"title":"AlltServerState.ready","type":"topic","url":"\/documentation\/alltkit\/alltserverstate\/ready","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/ready","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ready","kind":"identifier"}],"abstract":[{"type":"text","text":"The alltServer is not connected to a network"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AlltServerStateReady","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AlltServerStateReady","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AlltServerStateReady","kind":"identifier"}],"languages":["occ"]}]}},{"value":"AlltServerState","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"kind":"identifier","text":"AlltServerState"}]},{"value":"AlltServerStateReady","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1ready\/title","op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1ready\/fragments","op":"replace","value":[{"kind":"identifier","text":"AlltServerStateReady"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}