{"sections":[],"variants":[{"paths":["\/documentation\/alltkit\/alltserverstate\/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/alltkit\/alltserverstate\/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@AlltKit@E@AlltServerState@AlltServerStateStopped","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AlltServerStateStopped"}],"modules":[{"name":"AlltKit"}],"roleHeading":"Case","role":"symbol","title":"AlltServerState.stopped"},"hierarchy":{"paths":[["doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/stopped","interfaceLanguage":"swift"},"abstract":[{"text":"The alltServer is  connected to a network and media is currently playing","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopped"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState":{"title":"AlltServerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlltServerState","kind":"identifier"}],"abstract":[{"text":"Enumerates the possible states of the AlltServer","type":"text"}],"url":"\/documentation\/alltkit\/alltserverstate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlltServerState"}],"kind":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState"},"doc://tv.allt.AlltKit/documentation/AlltKit/AlltServerState/stopped":{"navigatorTitle":[{"text":"AlltServerStateStopped","kind":"identifier"}],"title":"AlltServerState.stopped","type":"topic","url":"\/documentation\/alltkit\/alltserverstate\/stopped","kind":"symbol","role":"symbol","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit\/AlltServerState\/stopped","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"abstract":[{"type":"text","text":"The alltServer is  connected to a network and media is currently playing"}]},"doc://tv.allt.AlltKit/documentation/AlltKit":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable the Allt experience within your own Apps.  AlltKit supports iOS and tvOS targets."}],"title":"AlltKit","identifier":"doc:\/\/tv.allt.AlltKit\/documentation\/AlltKit","url":"\/documentation\/alltkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AlltServerStateStopped","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlltServerStateStopped"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AlltServerStateStopped","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/title","value":"AlltServerState"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState\/fragments","value":[{"text":"AlltServerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1stopped\/title","value":"AlltServerStateStopped","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tv.allt.AlltKit~1documentation~1AlltKit~1AlltServerState~1stopped\/fragments","value":[{"kind":"identifier","text":"AlltServerStateStopped"}]}]}]}